source:      .
destination: ./_site
github: NortonLee
author: 'Norton.Li|李驰'
baseurl:     '/articles'
gems:  [tzinfo]
markdown: kramdown
markdown_ext:  markdown,mkd,mkdn,md
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title‹Hi,I'm·Norton›
all_categories: [
  ["tech", "技术","/posts/tech.html"], 
  ["tools", "工具","/posts/tools.html"]
]
# paginate: 8